name: Release

on:
  push:
    tags:
      - "v*"   # run only on version tags like v0.5.0

permissions:
  contents: write   # allow creating GitHub Releases and uploading artefacts

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history so GoReleaser can calculate next tag/changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest         # installs latest GoReleaser
          args: release --clean   # build + publish using .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # token provided by GitHub, sufficient for releases
